import type { ScanResult } from './types'

export const demoScanResult: ScanResult = {
  kernel: {
    version: '6.8.0-generic',
    config: {
      CONFIG_RANDOMIZE_BASE: 'y',
      CONFIG_STRICT_KERNEL_RWX: 'y',
      CONFIG_STACKPROTECTOR_STRONG: 'y',
      CONFIG_DEBUG_RODATA: 'y',
    },
    is_root: false,
  },
  daemons: [
    {
      port: 5432,
      protocol: 'tcp',
      address: '0.0.0.0',
      exposure: 'External',
      pid: 1274,
      binary_path: '/usr/lib/postgresql/15/bin/postgres',
      user: 'postgres',
      privilege_level: 'USER',
      description: 'postgresql',
      cpe: 'cpe:2.3:a:postgresql:postgresql:15:*:*:*:*:*:*:*',
      version: '15',
      is_reachable: true,
      memory_regions: [
        ['7f96a3c00000-7f96a3c91000', 'r-xp'],
        ['7f96a3d91000-7f96a3da2000', 'r--p'],
      ],
      risk: {
        score: 84,
        level: 'High',
        impact: 9,
        feasibility: 8,
        reason: 'Externally exposed daemon with reachable executable memory and known CVEs.',
      },
      vulnerabilities: [
        {
          cve_id: 'CVE-2024-0985',
          severity: 'HIGH',
          cvss_score: 8.1,
          description:
            'Sample PostgreSQL vulnerability used for interface validation.',
          affected_versions: ['15.x'],
          exploits: [{ source: 'public-reference' }],
          fixed_in: '15.6',
        },
        {
          cve_id: 'CVE-2023-5868',
          severity: 'MEDIUM',
          cvss_score: 6.5,
          description:
            'Sample vulnerability for validating secondary CVE display.',
          affected_versions: ['15.x'],
          fixed_in: '15.5',
        },
      ],
    },
    {
      port: 22,
      protocol: 'tcp',
      address: '127.0.0.1',
      exposure: 'Internal',
      pid: 947,
      binary_path: '/usr/sbin/sshd',
      user: 'root',
      privilege_level: 'ROOT',
      description: 'openssh-server',
      cpe: 'cpe:2.3:a:openbsd:openssh:9.6:*:*:*:*:*:*:*',
      version: '9.6',
      is_reachable: true,
      memory_regions: [['7f01a8000000-7f01a8091000', 'r-xp']],
      risk: {
        score: 48,
        level: 'Medium',
        impact: 8,
        feasibility: 5,
        reason: 'Privileged service is reachable but loopback-only.',
      },
      vulnerabilities: [],
    },
  ],
  binaries: [
    {
      path: '/usr/bin/sudo',
      sha256: 'sample-sha256-sudo',
      permissions: '-rwsr-xr-x',
      is_setuid: true,
      is_setgid: false,
      mitigations: {
        nx: true,
        pie: true,
        relro: 'full',
        canary: true,
      },
      privilege_level: 'ROOT',
      cpe: 'cpe:2.3:a:sudo_project:sudo:1.9.14:*:*:*:*:*:*:*',
      version: '1.9.14',
      is_reachable: false,
      memory_regions: [],
      risk: {
        score: 42,
        level: 'Medium',
        impact: 9,
        feasibility: 4,
        reason: 'Setuid binary with hardening enabled and no live memory mapping.',
      },
      vulnerabilities: [
        {
          cve_id: 'CVE-2023-42465',
          severity: 'MEDIUM',
          cvss_score: 6.7,
          description: 'Sample sudo vulnerability for table and graph validation.',
          affected_versions: ['1.9.x'],
          fixed_in: '1.9.15',
        },
      ],
    },
    {
      path: '/usr/bin/curl',
      sha256: 'sample-sha256-curl',
      permissions: '-rwxr-xr-x',
      is_setuid: false,
      is_setgid: false,
      mitigations: {
        nx: true,
        pie: true,
        relro: 'full',
      },
      privilege_level: 'USER',
      cpe: 'cpe:2.3:a:haxx:curl:8.5.0:*:*:*:*:*:*:*',
      version: '8.5.0',
      is_reachable: true,
      memory_regions: [['7f42b5000000-7f42b5060000', 'r-xp']],
      risk: {
        score: 24,
        level: 'Low',
        impact: 5,
        feasibility: 4,
        reason: 'User-level binary with active mapping and no high-severity CVE.',
      },
      vulnerabilities: [],
    },
  ],
  overall_risk_score: 67,
  overall_risk_level: 'High',
  timestamp: '2026-05-27T10:00:00',
}
